export type Payment = {
	id: string;
	amount: number;
	status: "Pending" | "Processing" | "Success" | "Failed";
	email: string;
	startDate: string;
	endDate: string;
	isActive: boolean;
	category: string;
};

export const dataTableData: Payment[] = [
    {
        id: "m5gr84i9",
        amount: 316,
        status: "Success",
        email: "ken99@yahoo.com",
        startDate: "2024-01-15",
        endDate: "2024-02-20",
        isActive: true,
        category: "Electronics",
    },
    {
        id: "3u1reuv4",
        amount: 242,
        status: "Success",
        email: "Abe45@gmail.com",
        startDate: "2024-02-01",
        endDate: "2024-03-15",
        isActive: true,
        category: "Clothing",
    },
    {
        id: "derv1ws0",
        amount: 837,
        status: "Processing",
        email: "Monserrat44@gmail.com",
        startDate: "2024-01-20",
        endDate: "2024-02-28",
        isActive: true,
        category: "Food",
    },
    {
        id: "5kma53ae",
        amount: 874,
        status: "Success",
        email: "Silas22@gmail.com",
        startDate: "2024-03-01",
        endDate: "2024-04-10",
        isActive: true,
        category: "Books",
    },
    {
        id: "bhqecj4p",
        amount: 721,
        status: "Failed",
        email: "carmella@hotmail.com",
        startDate: "2024-02-10",
        endDate: "2024-03-25",
        isActive: false,
        category: "Services",
    },
    {
        id: "7f8g9h0i",
        amount: 1250,
        status: "Success",
        email: "sarah.johnson@outlook.com",
        startDate: "2024-03-05",
        endDate: "2024-04-20",
        isActive: false,
        category: "Software",
    },
    {
        id: "j1k2l3m4",
        amount: 543,
        status: "Pending",
        email: "mike.wilson@company.com",
        startDate: "2024-01-10",
        endDate: "2024-02-15",
        isActive: false,
        category: "Hardware",
    },
    {
        id: "n5o6p7q8",
        amount: 892,
        status: "Success",
        email: "lisa.chen@startup.io",
        startDate: "2024-02-15",
        endDate: "2024-03-30",
        isActive: false,
        category: "Accessories",
    },
    {
        id: "r9s0t1u2",
        amount: 1567,
        status: "Processing",
        email: "david.brown@enterprise.net",
        startDate: "2024-01-25",
        endDate: "2024-03-10",
        isActive: false,
        category: "Tools",
    },
    {
        id: "v3w4x5y6",
        amount: 234,
        status: "Failed",
        email: "emma.davis@freelance.dev",
        startDate: "2024-02-20",
        endDate: "2024-04-05",
        isActive: false,
        category: "Media",
    },
    {
        id: "z7a8b9c0",
        amount: 678,
        status: "Success",
        email: "james.miller@consulting.co",
        startDate: "2024-03-10",
        endDate: "2024-04-25",
        isActive: true,
        category: "Electronics",
    },
    {
        id: "d1e2f3g4",
        amount: 945,
        status: "Pending",
        email: "anna.rodriguez@agency.com",
        startDate: "2024-01-05",
        endDate: "2024-02-18",
        isActive: true,
        category: "Clothing",
    },
    {
        id: "h5i6j7k8",
        amount: 1123,
        status: "Success",
        email: "robert.taylor@corporate.org",
        startDate: "2024-02-25",
        endDate: "2024-04-08",
        isActive: true,
        category: "Food",
    },
    {
        id: "l9m0n1o2",
        amount: 456,
        status: "Processing",
        email: "maria.garcia@smallbiz.com",
        startDate: "2024-01-30",
        endDate: "2024-03-12",
        isActive: true,
        category: "Books",
    },
    {
        id: "p3q4r5s6",
        amount: 789,
        status: "Failed",
        email: "thomas.anderson@techstartup.com",
        startDate: "2024-02-05",
        endDate: "2024-03-20",
        isActive: true,
        category: "Services",
    },
    {
        id: "t7u8v9w0",
        amount: 1345,
        status: "Success",
        email: "jennifer.lee@designstudio.com",
        startDate: "2024-03-15",
        endDate: "2024-05-01",
        isActive: true,
        category: "Software",
    },
    {
        id: "x1y2z3a4",
        amount: 567,
        status: "Pending",
        email: "christopher.white@consultant.net",
        startDate: "2024-01-18",
        endDate: "2024-02-28",
        isActive: true,
        category: "Hardware",
    },
    {
        id: "b5c6d7e8",
        amount: 987,
        status: "Success",
        email: "amanda.clark@marketing.co",
        startDate: "2024-02-12",
        endDate: "2024-03-27",
        isActive: true,
        category: "Accessories",
    },
    {
        id: "f9g0h1i2",
        amount: 432,
        status: "Processing",
        email: "daniel.martinez@services.io",
        startDate: "2024-01-22",
        endDate: "2024-03-05",
        isActive: false,
        category: "Tools",
    },
    {
        id: "j3k4l5m6",
        amount: 765,
        status: "Failed",
        email: "rebecca.thompson@creative.com",
        startDate: "2024-02-28",
        endDate: "2024-04-12",
        isActive: false,
        category: "Media",
    },
    {
        id: "n7o8p9q0",
        amount: 1890,
        status: "Success",
        email: "kevin.lewis@enterprise.com",
        startDate: "2024-03-08",
        endDate: "2024-04-22",
        isActive: false,
        category: "Electronics",
    },
    {
        id: "r1s2t3u4",
        amount: 654,
        status: "Pending",
        email: "rachel.green@startup.net",
        startDate: "2024-01-12",
        endDate: "2024-02-25",
        isActive: false,
        category: "Clothing",
    },
    {
        id: "v5w6x7y8",
        amount: 1234,
        status: "Success",
        email: "steven.king@corporation.org",
        startDate: "2024-02-18",
        endDate: "2024-04-02",
        isActive: false,
        category: "Food",
    },
    {
        id: "z9a0b1c2",
        amount: 876,
        status: "Processing",
        email: "laura.adams@agency.io",
        startDate: "2024-01-28",
        endDate: "2024-03-10",
        isActive: true,
        category: "Books",
    },
    {
        id: "d3e4f5g6",
        amount: 543,
        status: "Failed",
        email: "michael.campbell@freelance.com",
        startDate: "2024-02-08",
        endDate: "2024-03-22",
        isActive: false,
        category: "Services",
    },
    {
        id: "h7i8j9k0",
        amount: 2100,
        status: "Success",
        email: "nicole.young@consulting.net",
        startDate: "2024-03-12",
        endDate: "2024-04-28",
        isActive: false,
        category: "Software",
    },
    {
        id: "l1m2n3o4",
        amount: 345,
        status: "Pending",
        email: "jason.hall@smallbusiness.co",
        startDate: "2024-01-08",
        endDate: "2024-02-20",
        isActive: true,
        category: "Hardware",
    },
    {
        id: "p5q6r7s8",
        amount: 678,
        status: "Success",
        email: "ashley.turner@design.com",
        startDate: "2024-02-22",
        endDate: "2024-04-05",
        isActive: true,
        category: "Accessories",
    },
    {
        id: "t9u0v1w2",
        amount: 987,
        status: "Processing",
        email: "brandon.phillips@tech.io",
        startDate: "2024-01-14",
        endDate: "2024-02-27",
        isActive: true,
        category: "Tools",
    },
    {
        id: "x3y4z5a6",
        amount: 432,
        status: "Failed",
        email: "samantha.evans@creative.net",
        startDate: "2024-03-02",
        endDate: "2024-04-15",
        isActive: true,
        category: "Media",
    },
    {
        id: "b7c8d9e0",
        amount: 1567,
        status: "Success",
        email: "ryan.edwards@marketing.org",
        startDate: "2024-02-14",
        endDate: "2024-03-29",
        isActive: false,
        category: "Electronics",
    },
    {
        id: "f1g2h3i4",
        amount: 789,
        status: "Pending",
        email: "stephanie.collins@services.com",
        startDate: "2024-01-16",
        endDate: "2024-03-01",
        isActive: true,
        category: "Clothing",
    },
    {
        id: "j5k6l7m8",
        amount: 2345,
        status: "Success",
        email: "tyler.stewart@enterprise.co",
        startDate: "2024-03-18",
        endDate: "2024-05-03",
        isActive: true,
        category: "Food",
    },
    {
        id: "n9o0p1q2",
        amount: 567,
        status: "Processing",
        email: "hannah.morris@startup.net",
        startDate: "2024-02-03",
        endDate: "2024-03-18",
        isActive: false,
        category: "Books",
    },
    {
        id: "r3s4t5u6",
        amount: 890,
        status: "Failed",
        email: "justin.rogers@freelance.io",
        startDate: "2024-01-26",
        endDate: "2024-03-08",
        isActive: true,
        category: "Services",
    },
    {
        id: "v7w8x9y0",
        amount: 1234,
        status: "Success",
        email: "melissa.reed@corporation.com",
        startDate: "2024-02-24",
        endDate: "2024-04-07",
        isActive: false,
        category: "Software",
    },
    {
        id: "z1a2b3c4",
        amount: 678,
        status: "Pending",
        email: "andrew.cook@agency.org",
        startDate: "2024-01-11",
        endDate: "2024-02-24",
        isActive: true,
        category: "Hardware",
    },
    {
        id: "d5e6f7g8",
        amount: 1456,
        status: "Success",
        email: "jessica.morgan@consulting.net",
        startDate: "2024-03-06",
        endDate: "2024-04-20",
        isActive: true,
        category: "Accessories",
    },
    {
        id: "h9i0j1k2",
        amount: 432,
        status: "Processing",
        email: "matthew.bell@design.co",
        startDate: "2024-02-07",
        endDate: "2024-03-21",
        isActive: true,
        category: "Tools",
    },
    {
        id: "l3m4n5o6",
        amount: 987,
        status: "Failed",
        email: "elizabeth.murphy@tech.com",
        startDate: "2024-01-19",
        endDate: "2024-03-03",
        isActive: true,
        category: "Media",
    },
    {
        id: "p7q8r9s0",
        amount: 1789,
        status: "Success",
        email: "joshua.bailey@marketing.io",
        startDate: "2024-03-11",
        endDate: "2024-04-26",
        isActive: true,
        category: "Electronics",
    },
    {
        id: "t1u2v3w4",
        amount: 654,
        status: "Pending",
        email: "victoria.cooper@services.net",
        startDate: "2024-01-13",
        endDate: "2024-02-26",
        isActive: true,
        category: "Clothing",
    },
    {
        id: "x5y6z7a8",
        amount: 1123,
        status: "Success",
        email: "nathan.richardson@enterprise.org",
        startDate: "2024-02-17",
        endDate: "2024-04-01",
        isActive: true,
        category: "Food",
    },
    {
        id: "b9c0d1e2",
        amount: 456,
        status: "Processing",
        email: "christina.cox@startup.com",
        startDate: "2024-01-27",
        endDate: "2024-03-09",
        isActive: true,
        category: "Books",
    },
    {
        id: "f3g4h5i6",
        amount: 789,
        status: "Failed",
        email: "samuel.howard@freelance.co",
        startDate: "2024-02-11",
        endDate: "2024-03-26",
        isActive: true,
        category: "Services",
    },
    {
        id: "j7k8l9m0",
        amount: 2345,
        status: "Success",
        email: "danielle.ward@corporation.net",
        startDate: "2024-03-14",
        endDate: "2024-04-29",
        isActive: false,
        category: "Software",
    },
    {
        id: "n1o2p3q4",
        amount: 567,
        status: "Pending",
        email: "benjamin.torres@agency.io",
        startDate: "2024-01-09",
        endDate: "2024-02-22",
        isActive: true,
        category: "Hardware",
    },
    {
        id: "r5s6t7u8",
        amount: 890,
        status: "Success",
        email: "madison.peterson@consulting.com",
        startDate: "2024-02-21",
        endDate: "2024-04-04",
        isActive: true,
        category: "Accessories",
    },
    {
        id: "v9w0x1y2",
        amount: 1234,
        status: "Processing",
        email: "alexander.gray@design.net",
        startDate: "2024-01-23",
        endDate: "2024-03-06",
        isActive: true,
        category: "Tools",
    },
    {
        id: "z3a4b5c6",
        amount: 678,
        status: "Failed",
        email: "sophia.ramirez@tech.org",
        startDate: "2024-02-26",
        endDate: "2024-04-10",
        isActive: false,
        category: "Media",
    },
    {
        id: "d7e8f9g0",
        amount: 1567,
        status: "Success",
        email: "isaac.james@marketing.co",
        startDate: "2024-03-09",
        endDate: "2024-04-23",
        isActive: true,
        category: "Electronics",
    },
    {
        id: "h1i2j3k4",
        amount: 432,
        status: "Pending",
        email: "olivia.watson@services.com",
        startDate: "2024-01-07",
        endDate: "2024-02-19",
        isActive: false,
        category: "Clothing",
    },
    {
        id: "l5m6n7o8",
        amount: 987,
        status: "Success",
        email: "gabriel.brooks@enterprise.io",
        startDate: "2024-02-19",
        endDate: "2024-04-03",
        isActive: false,
        category: "Food",
    },
    {
        id: "p9q0r1s2",
        amount: 1789,
        status: "Processing",
        email: "ava.kelly@startup.net",
        startDate: "2024-01-21",
        endDate: "2024-03-04",
        isActive: true,
        category: "Books",
    },
    {
        id: "t3u4v5w6",
        amount: 654,
        status: "Failed",
        email: "logan.sanders@freelance.org",
        startDate: "2024-03-04",
        endDate: "2024-04-17",
        isActive: true,
        category: "Services",
    },
    {
        id: "x7y8z9a0",
        amount: 1123,
        status: "Success",
        email: "emily.price@corporation.co",
        startDate: "2024-02-13",
        endDate: "2024-03-28",
        isActive: true,
        category: "Software",
    },
    {
        id: "b1c2d3e4",
        amount: 456,
        status: "Pending",
        email: "carter.bennett@agency.com",
        startDate: "2024-01-17",
        endDate: "2024-03-01",
        isActive: true,
        category: "Hardware",
    },
    {
        id: "f5g6h7i8",
        amount: 789,
        status: "Success",
        email: "scarlett.wood@consulting.io",
        startDate: "2024-03-07",
        endDate: "2024-04-21",
        isActive: true,
        category: "Accessories",
    },
    {
        id: "j9k0l1m2",
        amount: 2345,
        status: "Processing",
        email: "owen.barnes@design.net",
        startDate: "2024-02-02",
        endDate: "2024-03-17",
        isActive: false,
        category: "Tools",
    },
    {
        id: "n3o4p5q6",
        amount: 567,
        status: "Failed",
        email: "chloe.ross@tech.com",
        startDate: "2024-01-24",
        endDate: "2024-03-07",
        isActive: false,
        category: "Media",
    },
    {
        id: "r7s8t9u0",
        amount: 890,
        status: "Success",
        email: "henry.henderson@marketing.org",
        startDate: "2024-03-13",
        endDate: "2024-04-27",
        isActive: false,
        category: "Electronics",
    },
    {
        id: "v1w2x3y4",
        amount: 1234,
        status: "Pending",
        email: "lily.coleman@services.co",
        startDate: "2024-01-06",
        endDate: "2024-02-18",
        isActive: true,
        category: "Clothing",
    },
    {
        id: "z5a6b7c8",
        amount: 678,
        status: "Success",
        email: "sebastian.jenkins@enterprise.net",
        startDate: "2024-02-16",
        endDate: "2024-03-31",
        isActive: false,
        category: "Food",
    },
    // Test cases for prioritized search with "anne"
    {
        id: "anne-exact-1",
        amount: 500,
        status: "Success",
        email: "anne@example.com",
        startDate: "2024-01-01",
        endDate: "2024-02-15",
        isActive: false,
        category: "Books",
    },
    {
        id: "anne-exact-2",
        amount: 600,
        status: "Pending",
        email: "Anne.Smith@company.com",
        startDate: "2024-02-01",
        endDate: "2024-03-16",
        isActive: false,
        category: "Services",
    },
    {
        id: "anne-start-1",
        amount: 700,
        status: "Processing",
        email: "annemarie@example.com",
        startDate: "2024-01-15",
        endDate: "2024-03-01",
        isActive: false,
        category: "Software",
    },
    {
        id: "anne-start-2",
        amount: 800,
        status: "Success",
        email: "Annemarie.Johnson@company.com",
        startDate: "2024-02-15",
        endDate: "2024-04-01",
        isActive: true,
        category: "Hardware",
    },
    {
        id: "anne-end-1",
        amount: 900,
        status: "Success",
        email: "susanne@example.com",
        startDate: "2024-01-20",
        endDate: "2024-03-05",
        isActive: true,
        category: "Accessories",
    },
    {
        id: "anne-end-2",
        amount: 1000,
        status: "Pending",
        email: "Susanne.Williams@company.com",
        startDate: "2024-02-20",
        endDate: "2024-04-05",
        isActive: false,
        category: "Tools",
    },
    {
        id: "anne-middle-1",
        amount: 1100,
        status: "Processing",
        email: "hannes@example.com",
        startDate: "2024-01-10",
        endDate: "2024-02-24",
        isActive: true,
        category: "Media",
    },
    {
        id: "anne-middle-2",
        amount: 1200,
        status: "Success",
        email: "Hannes.Brown@company.com",
        startDate: "2024-02-10",
        endDate: "2024-03-25",
        isActive: true,
        category: "Electronics",
    }
]
