export type Payment = {
		id: string;
		amount: number;
		status: "Pending" | "Processing" | "Success" | "Failed";
		email: string;
	};

export const dataTableData: Payment[] = [
    {
        id: "m5gr84i9",
        amount: 316,
        status: "Success",
        email: "ken99@yahoo.com",
    },
    {
        id: "3u1reuv4",
        amount: 242,
        status: "Success",
        email: "Abe45@gmail.com",
    },
    {
        id: "derv1ws0",
        amount: 837,
        status: "Processing",
        email: "Monserrat44@gmail.com",
    },
    {
        id: "5kma53ae",
        amount: 874,
        status: "Success",
        email: "Silas22@gmail.com",
    },
    {
        id: "bhqecj4p",
        amount: 721,
        status: "Failed",
        email: "carmella@hotmail.com",
    },
    {
        id: "7f8g9h0i",
        amount: 1250,
        status: "Success",
        email: "sarah.johnson@outlook.com",
    },
    {
        id: "j1k2l3m4",
        amount: 543,
        status: "Pending",
        email: "mike.wilson@company.com",
    },
    {
        id: "n5o6p7q8",
        amount: 892,
        status: "Success",
        email: "lisa.chen@startup.io",
    },
    {
        id: "r9s0t1u2",
        amount: 1567,
        status: "Processing",
        email: "david.brown@enterprise.net",
    },
    {
        id: "v3w4x5y6",
        amount: 234,
        status: "Failed",
        email: "emma.davis@freelance.dev",
    },
    {
        id: "z7a8b9c0",
        amount: 678,
        status: "Success",
        email: "james.miller@consulting.co",
    },
    {
        id: "d1e2f3g4",
        amount: 945,
        status: "Pending",
        email: "anna.rodriguez@agency.com",
    },
    {
        id: "h5i6j7k8",
        amount: 1123,
        status: "Success",
        email: "robert.taylor@corporate.org",
    },
    {
        id: "l9m0n1o2",
        amount: 456,
        status: "Processing",
        email: "maria.garcia@smallbiz.com",
    },
    {
        id: "p3q4r5s6",
        amount: 789,
        status: "Failed",
        email: "thomas.anderson@techstartup.com",
    },
    {
        id: "t7u8v9w0",
        amount: 1345,
        status: "Success",
        email: "jennifer.lee@designstudio.com",
    },
    {
        id: "x1y2z3a4",
        amount: 567,
        status: "Pending",
        email: "christopher.white@consultant.net",
    },
    {
        id: "b5c6d7e8",
        amount: 987,
        status: "Success",
        email: "amanda.clark@marketing.co",
    },
    {
        id: "f9g0h1i2",
        amount: 432,
        status: "Processing",
        email: "daniel.martinez@services.io",
    },
    {
        id: "j3k4l5m6",
        amount: 765,
        status: "Failed",
        email: "rebecca.thompson@creative.com",
    },
    {
        id: "n7o8p9q0",
        amount: 1890,
        status: "Success",
        email: "kevin.lewis@enterprise.com",
    },
    {
        id: "r1s2t3u4",
        amount: 654,
        status: "Pending",
        email: "rachel.green@startup.net",
    },
    {
        id: "v5w6x7y8",
        amount: 1234,
        status: "Success",
        email: "steven.king@corporation.org",
    },
    {
        id: "z9a0b1c2",
        amount: 876,
        status: "Processing",
        email: "laura.adams@agency.io",
    },
    {
        id: "d3e4f5g6",
        amount: 543,
        status: "Failed",
        email: "michael.campbell@freelance.com",
    },
    {
        id: "h7i8j9k0",
        amount: 2100,
        status: "Success",
        email: "nicole.young@consulting.net",
    },
    {
        id: "l1m2n3o4",
        amount: 345,
        status: "Pending",
        email: "jason.hall@smallbusiness.co",
    },
    {
        id: "p5q6r7s8",
        amount: 678,
        status: "Success",
        email: "ashley.turner@design.com",
    },
    {
        id: "t9u0v1w2",
        amount: 987,
        status: "Processing",
        email: "brandon.phillips@tech.io",
    },
    {
        id: "x3y4z5a6",
        amount: 432,
        status: "Failed",
        email: "samantha.evans@creative.net",
    },
    {
        id: "b7c8d9e0",
        amount: 1567,
        status: "Success",
        email: "ryan.edwards@marketing.org",
    },
    {
        id: "f1g2h3i4",
        amount: 789,
        status: "Pending",
        email: "stephanie.collins@services.com",
    },
    {
        id: "j5k6l7m8",
        amount: 2345,
        status: "Success",
        email: "tyler.stewart@enterprise.co",
    },
    {
        id: "n9o0p1q2",
        amount: 567,
        status: "Processing",
        email: "hannah.morris@startup.net",
    },
    {
        id: "r3s4t5u6",
        amount: 890,
        status: "Failed",
        email: "justin.rogers@freelance.io",
    },
    {
        id: "v7w8x9y0",
        amount: 1234,
        status: "Success",
        email: "melissa.reed@corporation.com",
    },
    {
        id: "z1a2b3c4",
        amount: 678,
        status: "Pending",
        email: "andrew.cook@agency.org",
    },
    {
        id: "d5e6f7g8",
        amount: 1456,
        status: "Success",
        email: "jessica.morgan@consulting.net",
    },
    {
        id: "h9i0j1k2",
        amount: 432,
        status: "Processing",
        email: "matthew.bell@design.co",
    },
    {
        id: "l3m4n5o6",
        amount: 987,
        status: "Failed",
        email: "elizabeth.murphy@tech.com",
    },
    {
        id: "p7q8r9s0",
        amount: 1789,
        status: "Success",
        email: "joshua.bailey@marketing.io",
    },
    {
        id: "t1u2v3w4",
        amount: 654,
        status: "Pending",
        email: "victoria.cooper@services.net",
    },
    {
        id: "x5y6z7a8",
        amount: 1123,
        status: "Success",
        email: "nathan.richardson@enterprise.org",
    },
    {
        id: "b9c0d1e2",
        amount: 456,
        status: "Processing",
        email: "christina.cox@startup.com",
    },
    {
        id: "f3g4h5i6",
        amount: 789,
        status: "Failed",
        email: "samuel.howard@freelance.co",
    },
    {
        id: "j7k8l9m0",
        amount: 2345,
        status: "Success",
        email: "danielle.ward@corporation.net",
    },
    {
        id: "n1o2p3q4",
        amount: 567,
        status: "Pending",
        email: "benjamin.torres@agency.io",
    },
    {
        id: "r5s6t7u8",
        amount: 890,
        status: "Success",
        email: "madison.peterson@consulting.com",
    },
    {
        id: "v9w0x1y2",
        amount: 1234,
        status: "Processing",
        email: "alexander.gray@design.net",
    },
    {
        id: "z3a4b5c6",
        amount: 678,
        status: "Failed",
        email: "sophia.ramirez@tech.org",
    },
    {
        id: "d7e8f9g0",
        amount: 1567,
        status: "Success",
        email: "isaac.james@marketing.co",
    },
    {
        id: "h1i2j3k4",
        amount: 432,
        status: "Pending",
        email: "olivia.watson@services.com",
    },
    {
        id: "l5m6n7o8",
        amount: 987,
        status: "Success",
        email: "gabriel.brooks@enterprise.io",
    },
    {
        id: "p9q0r1s2",
        amount: 1789,
        status: "Processing",
        email: "ava.kelly@startup.net",
    },
    {
        id: "t3u4v5w6",
        amount: 654,
        status: "Failed",
        email: "logan.sanders@freelance.org",
    },
    {
        id: "x7y8z9a0",
        amount: 1123,
        status: "Success",
        email: "emily.price@corporation.co",
    },
    {
        id: "b1c2d3e4",
        amount: 456,
        status: "Pending",
        email: "carter.bennett@agency.com",
    },
    {
        id: "f5g6h7i8",
        amount: 789,
        status: "Success",
        email: "scarlett.wood@consulting.io",
    },
    {
        id: "j9k0l1m2",
        amount: 2345,
        status: "Processing",
        email: "owen.barnes@design.net",
    },
    {
        id: "n3o4p5q6",
        amount: 567,
        status: "Failed",
        email: "chloe.ross@tech.com",
    },
    {
        id: "r7s8t9u0",
        amount: 890,
        status: "Success",
        email: "henry.henderson@marketing.org",
    },
    {
        id: "v1w2x3y4",
        amount: 1234,
        status: "Pending",
        email: "lily.coleman@services.co",
    },
    {
        id: "z5a6b7c8",
        amount: 678,
        status: "Success",
        email: "sebastian.jenkins@enterprise.net",
    }
]